Repository pangseon/Extra, pull requests merged in 2024-08, with the labels that each got.

#25 Feature/read job post
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/mapper/dto/JobPostDtoMapper.java
  src/main/java/com/example/extra/domain/jobpost/mapper/service/JobPostEntityMapper.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/role/mapper/dto/RoleDtoMapper.java
  src/main/java/com/example/extra/domain/role/repository/RoleRepository.java
Labels: feature

#16 Feature/login logout/member
  build.gradle
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberLoginServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/extra/domain/member/exception/MemberException.java
  src/main/java/com/example/extra/domain/member/mapper/dto/MemberDtoMapper.java
  src/main/java/com/example/extra/domain/member/mapper/entity/MemberEntityMapper.java
  src/main/java/com/example/extra/domain/member/repository/MemberRepository.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/global/config/PasswordConfig.java
  src/main/java/com/example/extra/global/config/RedisConfig.java
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/enums/UserRole.java
  src/main/java/com/example/extra/global/exception/dto/TokenExceptionResponseDto.java
  src/main/java/com/example/extra/global/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/extra/global/exception/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/extra/global/security/JwtUtil.java
  src/main/java/com/example/extra/global/security/UserDetailsImpl.java
  src/main/java/com/example/extra/global/security/UserDetailsServiceImpl.java
  src/main/java/com/example/extra/global/security/controller/RefreshTokenController.java
  src/main/java/com/example/extra/global/security/dto/RefreshTokenCreateServiceResponseDto.java
  src/main/java/com/example/extra/global/security/exception/TokenErrorCode.java
  src/main/java/com/example/extra/global/security/exception/TokenException.java
  src/main/java/com/example/extra/global/security/repository/RefreshTokenRepository.java
  src/main/java/com/example/extra/global/security/service/RefreshTokenService.java
  src/main/java/com/example/extra/global/security/token/RefreshToken.java
Labels: feature

#31 Feature/create role
  src/main/java/com/example/extra/domain/jobpost/mapper/service/JobPostEntityMapper.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/role/controller/RoleController.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/RoleCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/exception/NotFoundRoleException.java
  src/main/java/com/example/extra/domain/role/exception/RoleErrorCode.java
  src/main/java/com/example/extra/domain/role/mapper/dto/RoleDtoMapper.java
  src/main/java/com/example/extra/domain/role/service/RoleService.java
  src/main/java/com/example/extra/domain/role/service/impl/RoleServiceImpl.java
  src/main/java/com/example/extra/domain/schedule/controller/ScheduleController.java
Labels: feature

#32 Feature/회원가입/company
  src/main/java/com/example/extra/domain/company/controller/CompanyController.java
  src/main/java/com/example/extra/domain/company/dto/controller/CompanyCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/controller/CompanyLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/service/request/CompanyCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/service/request/CompanyLoginServiceRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/service/response/CompanyLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/company/dto/service/response/CompanyReadOnceServiceResponseDto.java
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/company/exception/CompanyErrorCode.java
  src/main/java/com/example/extra/domain/company/exception/CompanyException.java
  src/main/java/com/example/extra/domain/company/mapper/dto/CompanyDtoMapper.java
  src/main/java/com/example/extra/domain/company/mapper/entity/CompanyEntityMapper.java
  src/main/java/com/example/extra/domain/company/repository/CompanyRepository.java
  src/main/java/com/example/extra/domain/company/service/CompanyService.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/com/example/extra/global/exception/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/extra/global/security/JwtUtil.java
  src/main/java/com/example/extra/global/security/UserDetailsImpl.java
  src/main/java/com/example/extra/global/security/UserDetailsServiceImpl.java
  src/main/java/com/example/extra/global/security/exception/TokenErrorCode.java
Labels: feature

#35 Refactor/코드 컨벤션 리팩토링/member
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
Labels: refactor

#37 Refactor/company job post
  build.gradle
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/dto/controller/JobPostCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/controller/JobPostUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/entity/JobPost.java
  src/main/java/com/example/extra/domain/jobpost/mapper/service/JobPostEntityMapper.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/repository/RoleRepository.java
  src/main/java/com/example/extra/domain/schedule/repository/ScheduleRepository.java
Labels: refactor

#33 Feature/save-qr-info/attendance-management
  build.gradle
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestCompanyController.java
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestMemberController.java
  src/main/java/com/example/extra/domain/applicationrequest/dto/service/ApplicationRequestCompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/applicationrequest/repository/ApplicationRequestMemberRepository.java
  src/main/java/com/example/extra/domain/applicationrequest/service/ApplicationRequestMemberService.java
  src/main/java/com/example/extra/domain/applicationrequest/service/impl/ApplicationRequestMemberServiceImpl.java
  src/main/java/com/example/extra/domain/attendancemanagement/controller/AttendanceManagementController.java
  src/main/java/com/example/extra/domain/attendancemanagement/dto/controller/AttendanceManagementUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/attendancemanagement/dto/service/AttendanceManagementCreateExcelServiceResponseDto.java
  src/main/java/com/example/extra/domain/attendancemanagement/dto/service/AttendanceManagementReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/attendancemanagement/dto/service/AttendanceManagementUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/attendancemanagement/entity/AttendanceManagement.java
  src/main/java/com/example/extra/domain/attendancemanagement/exception/AlreadyClockedInException.java
  src/main/java/com/example/extra/domain/attendancemanagement/exception/AlreadyClockedOutException.java
  src/main/java/com/example/extra/domain/attendancemanagement/exception/AttendanceManagementErrorCode.java
  src/main/java/com/example/extra/domain/attendancemanagement/exception/NotFoundAttendanceManagementException.java
  src/main/java/com/example/extra/domain/attendancemanagement/mapper/dto/AttendanceManagementDtoMapper.java
  src/main/java/com/example/extra/domain/attendancemanagement/mapper/entity/AttendanceManagementEntityMapper.java
  src/main/java/com/example/extra/domain/attendancemanagement/repository/AttendanceManagementRepository.java
  src/main/java/com/example/extra/domain/attendancemanagement/service/AttendanceManagementService.java
  src/main/java/com/example/extra/domain/attendancemanagement/service/impl/AttendanceManagementServiceImpl.java
  src/main/java/com/example/extra/domain/attendancemanagement/util/ExcelFile.java
  src/main/java/com/example/extra/domain/member/repository/MemberRepository.java
  src/main/java/com/example/extra/domain/role/repository/RoleRepository.java
Labels: feature

#45 Feature/의상 로직 준비/costume approval board
  src/main/java/com/example/extra/domain/costumeapprovalboard/CostumeApprovalBoard/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardException.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/repository/CostumeApprovalBoardRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#39 Feature/update role
  src/main/java/com/example/extra/domain/role/controller/RoleController.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/RoleUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/mapper/dto/RoleDtoMapper.java
  src/main/java/com/example/extra/domain/role/repository/RoleRepository.java
  src/main/java/com/example/extra/domain/role/service/RoleService.java
  src/main/java/com/example/extra/domain/role/service/impl/RoleServiceImpl.java
Labels: feature

#51 Feautre/update schedule
  src/main/java/com/example/extra/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/extra/domain/schedule/dto/controller/ScheduleUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/schedule/dto/service/request/ScheduleCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/schedule/dto/service/request/ScheduleUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/schedule/entity/Schedule.java
  src/main/java/com/example/extra/domain/schedule/mapper/dto/ScheduleDtoMapper.java
  src/main/java/com/example/extra/domain/schedule/mapper/service/ScheduleEntityMapper.java
  src/main/java/com/example/extra/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/example/extra/domain/schedule/service/ScheduleService.java
  src/main/java/com/example/extra/domain/schedule/service/impl/ScheduleServiceImpl.java
Labels: feature, refactor

#56 Feature/의상 승인 게시판 글 작성/costume approval board
  src/main/java/com/example/extra/domain/applicationrequest/exception/ApplicationRequestErrorCode.java
  src/main/java/com/example/extra/domain/applicationrequest/exception/ApplicationRequestException.java
  src/main/java/com/example/extra/domain/applicationrequest/repository/ApplicationRequestCompanyRepository.java
  src/main/java/com/example/extra/domain/applicationrequest/repository/ApplicationRequestMemberRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/CostumeApprovalBoard/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainCreateRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCreateServiceDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/mapper/dto/CostumeApprovalBoardDtoMapper.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/repository/CostumeApprovalBoardRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#59 Refactor/회사 리팩토링/company
  src/main/java/com/example/extra/domain/company/controller/CompanyController.java
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/company/exception/CompanyErrorCode.java
  src/main/java/com/example/extra/domain/company/repository/CompanyRepository.java
  src/main/java/com/example/extra/domain/company/service/CompanyService.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/extra/global/security/JwtUtil.java
  src/main/java/com/example/extra/global/security/UserDetailsImpl.java
Labels: refactor

#64 Feature/s3 setting
  build.gradle
  src/main/java/com/example/extra/global/config/S3Config.java
Labels: feature

#47 Feature/read costume approval board for member/costume approval board
  src/main/java/com/example/extra/domain/costumeapprovalboard/CostumeApprovalBoard/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/repository/CostumeApprovalBoardRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#49 Feature/delete costume approval board member/costume approval board
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#65 Feature/read all costume approval board/costume approval board
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/repository/CostumeApprovalBoardRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#68 Feature/의상 승인 게시판 글 수정/costume approval board
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardExplainUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/mapper/dto/CostumeApprovalBoardDtoMapper.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#70 Feature/의상 승인 게시판 글 승인
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardApplyStatusUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardApplyStatusUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadDetailServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/mapper/dto/CostumeApprovalBoardDtoMapper.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#72 Feature/use login info/application request
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestCompanyController.java
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestMemberController.java
  src/main/java/com/example/extra/domain/applicationrequest/dto/controller/ApplicationRequestMemberUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/applicationrequest/entity/ApplicationRequest.java
  src/main/java/com/example/extra/domain/applicationrequest/exception/ApplicationRequestErrorCode.java
  src/main/java/com/example/extra/domain/applicationrequest/exception/NotAbleToApplyToJobPostException.java
  src/main/java/com/example/extra/domain/applicationrequest/exception/NotAbleToCancelApplicationRequestMemberException.java
  src/main/java/com/example/extra/domain/applicationrequest/exception/NotFoundApplicationRequestCompanyException.java
  src/main/java/com/example/extra/domain/applicationrequest/exception/NotFoundApplicationRequestMemberException.java
  src/main/java/com/example/extra/domain/applicationrequest/service/ApplicationRequestMemberService.java
  src/main/java/com/example/extra/domain/applicationrequest/service/impl/ApplicationRequestMemberServiceImpl.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardApplyStatusUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardApplyStatusUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/exception/CostumeApprovalBoardErrorCode.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature, refactor

#76 Refactor: snake case 필드 이름 전부 camel case로 변경
  src/main/java/com/example/extra/domain/attendancemanagement/service/impl/AttendanceManagementServiceImpl.java
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadDetailServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/role/controller/RoleController.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/extra/global/security/JwtUtil.java
  src/main/java/com/example/extra/global/security/UserDetailsImpl.java
Labels: bug

#78 Refactor/costume approval board
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/global/s3/S3Provider.java
Labels: refactor

#81 Feature/redis key type 변경
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/company/repository/CompanyRepository.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/extra/global/security/controller/RefreshTokenController.java
  src/main/java/com/example/extra/global/security/repository/RefreshTokenRepository.java
  src/main/java/com/example/extra/global/security/service/RefreshTokenService.java
  src/main/java/com/example/extra/global/security/token/RefreshToken.java
Labels: feature

#89 Feature/swagger 추가
  build.gradle
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/config/SwaggerConfig.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
Labels: feature

#92 Feature/테스트 용도 파일 작성 및 수정
  Dockerfile
  src/main/java/com/example/extra/global/config/RedisConfig.java
Labels: feature

#99 Feature/refactor tattoo/tattoo
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/domain/tattoo/dto/controller/TattooCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/tattoo/dto/service/request/TattooCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/tattoo/entity/Tattoo.java
  src/main/java/com/example/extra/domain/tattoo/mapper/entity/TattooEntityMapper.java
  src/main/java/com/example/extra/domain/tattoo/repository/TattooRepository.java
Labels: refactor

#100 Feature/member company 통합
  src/main/java/com/example/extra/domain/account/controller/AccountController.java
  src/main/java/com/example/extra/domain/account/dto/controller/AccountCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/controller/AccountLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/service/request/AccountCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/service/request/AccountLoginServiceRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/service/response/AccountCreateServiceResponseDto.java
  src/main/java/com/example/extra/domain/account/dto/service/response/AccountLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/account/entity/Account.java
  src/main/java/com/example/extra/domain/account/exception/AccountErrorCode.java
  src/main/java/com/example/extra/domain/account/exception/AccountException.java
  src/main/java/com/example/extra/domain/account/mapper/dto/AccountDtoMapper.java
  src/main/java/com/example/extra/domain/account/mapper/entity/AccountEntityMapper.java
  src/main/java/com/example/extra/domain/account/repository/AccountRepository.java
  src/main/java/com/example/extra/domain/account/service/AccountService.java
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestMemberController.java
  src/main/java/com/example/extra/domain/applicationrequest/service/ApplicationRequestMemberService.java
  src/main/java/com/example/extra/domain/applicationrequest/service/impl/ApplicationRequestMemberServiceImpl.java
  src/main/java/com/example/extra/domain/attendancemanagement/controller/AttendanceManagementController.java
  src/main/java/com/example/extra/domain/attendancemanagement/service/AttendanceManagementService.java
  src/main/java/com/example/extra/domain/attendancemanagement/service/impl/AttendanceManagementServiceImpl.java
  src/main/java/com/example/extra/domain/company/controller/CompanyController.java
  src/main/java/com/example/extra/domain/company/dto/controller/CompanyCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/service/request/CompanyCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/company/mapper/entity/CompanyEntityMapper.java
  src/main/java/com/example/extra/domain/company/repository/CompanyRepository.java
  src/main/java/com/example/extra/domain/company/service/CompanyService.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/mapper/entity/MemberEntityMapper.java
  src/main/java/com/example/extra/domain/member/repository/MemberRepository.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/domain/role/controller/RoleController.java
  src/main/java/com/example/extra/domain/role/service/RoleService.java
  src/main/java/com/example/extra/domain/role/service/impl/RoleServiceImpl.java
  src/main/java/com/example/extra/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/extra/domain/schedule/service/ScheduleService.java
  src/main/java/com/example/extra/domain/schedule/service/impl/ScheduleServiceImpl.java
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/enums/UserRole.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/extra/global/security/JwtUtil.java
  src/main/java/com/example/extra/global/security/UserDetailsImpl.java
  src/main/java/com/example/extra/global/security/UserDetailsServiceImpl.java
  src/main/java/com/example/extra/global/security/controller/RefreshTokenController.java
  src/main/java/com/example/extra/global/security/service/RefreshTokenService.java
Labels: refactor

#85 refactor : 공고글 조회 시 최신 날짜 순으로 조회하는 로직 추가
  src/main/java/com/example/extra/domain/applicationrequest/dto/service/ApplicationRequestMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/applicationrequest/mapper/entity/ApplicationRequestEntityMapper.java
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/dto/controller/JobPostCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/entity/JobPost.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/role/dto/service/request/RoleUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/service/impl/RoleServiceImpl.java
Labels: refactor

#102 Refactor/role age
  src/main/java/com/example/extra/domain/role/dto/controller/RoleCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/request/RoleCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/request/RoleUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/response/RoleServiceResponseDto.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/mapper/service/RoleEntityMapper.java
  src/main/java/com/example/extra/domain/role/service/impl/RoleServiceImpl.java
Labels: feature, refactor

#96 Feature/cors option
  src/main/java/com/example/extra/global/config/SecurityConfig.java
Labels: bug

#94 Feature/kakao login/member
  build.gradle
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/extra/domain/applicationrequest/dto/service/ApplicationRequestMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/applicationrequest/mapper/entity/ApplicationRequestEntityMapper.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/domain/jobpost/dto/controller/JobPostCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/entity/JobPost.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/domain/refreshtoken/controller/RefreshTokenController.java
  src/main/java/com/example/extra/domain/refreshtoken/dto/RefreshTokenCreateServiceResponseDto.java
  src/main/java/com/example/extra/domain/refreshtoken/exception/TokenErrorCode.java
  src/main/java/com/example/extra/domain/refreshtoken/exception/TokenException.java
  src/main/java/com/example/extra/domain/refreshtoken/repository/RefreshTokenRepository.java
  src/main/java/com/example/extra/domain/refreshtoken/service/RefreshTokenService.java
  src/main/java/com/example/extra/domain/refreshtoken/token/RefreshToken.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/request/RoleCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/response/RoleServiceResponseDto.java
  src/main/java/com/example/extra/domain/role/mapper/service/RoleEntityMapper.java
  src/main/java/com/example/extra/domain/tattoo/entity/Tattoo.java
  src/main/java/com/example/extra/global/config/SecurityConfig.java
  src/main/java/com/example/extra/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/extra/global/security/oauth/controller/KakaoController.java
  src/main/java/com/example/extra/global/security/oauth/dto/controller/KakaoLoginControllerRequestDto.java
  src/main/java/com/example/extra/global/security/oauth/dto/service/request/KakaoLoginServiceRequestDto.java
  src/main/java/com/example/extra/global/security/oauth/dto/service/response/KakaoLoginServiceResponseDto.java
  src/main/java/com/example/extra/global/security/oauth/dto/service/response/KakaoTokenInfoServiceResponseDto.java
  src/main/java/com/example/extra/global/security/oauth/entity/KakaoInfo.java
  src/main/java/com/example/extra/global/security/oauth/service/KakaoServiceImpl.java
Labels: feature

#106 Refactor/costume approveal board
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardExplainUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/repository/CostumeApprovalBoardRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/domain/tattoo/controller/TattooController.java
  src/main/java/com/example/extra/domain/tattoo/mapper/service/TattooEntityMapper.java
  src/main/java/com/example/extra/domain/tattoo/service/TattooService.java
  src/main/java/com/example/extra/domain/tattoo/service/impl/TattooServiceImpl.java
Labels: feature, refactor

#104 Feature : 타투 생성 기능 추가
  src/main/java/com/example/extra/domain/tattoo/controller/TattooController.java
  src/main/java/com/example/extra/domain/tattoo/mapper/service/TattooEntityMapper.java
  src/main/java/com/example/extra/domain/tattoo/service/TattooService.java
  src/main/java/com/example/extra/domain/tattoo/service/impl/TattooServiceImpl.java
Labels: feature

#108 Feature/카카오 가입자 로그인 처리
  src/main/java/com/example/extra/global/security/oauth/controller/KakaoController.java
  src/main/java/com/example/extra/global/security/oauth/dto/service/response/KakaoLoginCheckServiceResponseDto.java
  src/main/java/com/example/extra/global/security/oauth/service/KakaoServiceImpl.java
Labels: refactor

#110 Feature/카카오 로그인 반환 값 수정
  src/main/java/com/example/extra/global/security/oauth/controller/KakaoController.java
  src/main/java/com/example/extra/global/security/oauth/dto/service/response/KakaoSignupServiceResponseDto.java
  src/main/java/com/example/extra/global/security/oauth/service/KakaoServiceImpl.java
Labels: refactor

#116 Feature/카카오 로그인 인증 반환 변경
  src/main/java/com/example/extra/global/security/oauth/controller/KakaoController.java
  src/main/java/com/example/extra/global/security/oauth/dto/service/response/KakaoAuthServiceResponseDto.java
  src/main/java/com/example/extra/global/security/oauth/service/KakaoServiceImpl.java
Labels: refactor

#115 Feature/application request filtering
  build.gradle
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestMemberController.java
  src/main/java/com/example/extra/domain/applicationrequest/dto/service/ApplicationRequestCompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/applicationrequest/dto/service/ApplicationRequestMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/applicationrequest/mapper/entity/ApplicationRequestEntityMapper.java
  src/main/java/com/example/extra/domain/applicationrequest/repository/ApplicationRequestMemberRepository.java
  src/main/java/com/example/extra/domain/applicationrequest/service/ApplicationRequestMemberService.java
  src/main/java/com/example/extra/domain/applicationrequest/service/impl/ApplicationRequestMemberServiceImpl.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
Labels: feature

#118 Feature : 캘린더를 활용한 조회 기능 추가
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
Labels: feature, refactor

#119 Feature/프로필 이미지 세팅/account
  src/main/java/com/example/extra/domain/account/entity/Account.java
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/mapper/dto/MemberDtoMapper.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
Labels: feature

#121 Feature/costume approval board filter
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestMemberController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainCreateRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadDetailServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardCreateServiceDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardExplainUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/CostumeApprovalBoardMemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/repository/CostumeApprovalBoardRepository.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
Labels: feature

#123 Feature/attendance management search
  src/main/java/com/example/extra/domain/applicationrequest/repository/ApplicationRequestMemberRepository.java
  src/main/java/com/example/extra/domain/attendancemanagement/controller/AttendanceManagementController.java
  src/main/java/com/example/extra/domain/attendancemanagement/service/AttendanceManagementService.java
  src/main/java/com/example/extra/domain/attendancemanagement/service/impl/AttendanceManagementServiceImpl.java
Labels: feature

#126 Feature/fix jobpost
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostCreateServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
Labels: feature

#128 Feature/member 관련 리팩토링/member
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
Labels: refactor

#130 Feature/fix role
  src/main/java/com/example/extra/domain/applicationrequest/service/impl/ApplicationRequestMemberServiceImpl.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/response/JobPostReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/request/RoleCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/request/RoleUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/service/response/RoleServiceResponseDto.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/exception/RoleException.java
  src/main/java/com/example/extra/domain/role/mapper/dto/RoleDtoMapper.java
  src/main/java/com/example/extra/domain/role/mapper/service/RoleEntityMapper.java
  src/main/java/com/example/extra/domain/role/service/impl/RoleServiceImpl.java
  src/main/java/com/example/extra/domain/schedule/service/impl/ScheduleServiceImpl.java
  src/main/java/com/example/extra/domain/tattoo/dto/service/response/TattooReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/tattoo/exception/TattooErrorCode.java
  src/main/java/com/example/extra/domain/tattoo/exception/TattooException.java
  src/main/java/com/example/extra/domain/tattoo/repository/TattooRepository.java
Labels: feature

#132 Refactor/member dto
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberSignUpControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberLoginServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberCreateServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/mapper/dto/MemberDtoMapper.java
  src/main/java/com/example/extra/domain/member/mapper/entity/MemberEntityMapper.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/domain/tattoo/repository/TattooRepository.java
Labels: refactor

#139 Feature/refresh token 발급
  src/main/java/com/example/extra/domain/account/controller/AccountController.java
  src/main/java/com/example/extra/domain/account/dto/service/response/AccountLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/extra/domain/refreshtoken/controller/RefreshTokenController.java
  src/main/java/com/example/extra/domain/refreshtoken/dto/RefreshTokenCreateServiceResponseDto.java
  src/main/java/com/example/extra/domain/refreshtoken/service/RefreshTokenService.java
Labels: refactor

#141 Refactor/define db schema
  src/main/java/com/example/extra/domain/applicationrequest/entity/ApplicationRequest.java
  src/main/java/com/example/extra/domain/attendancemanagement/entity/AttendanceManagement.java
  src/main/java/com/example/extra/domain/company/controller/CompanyController.java
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/entity/CostumeApprovalBoard.java
  src/main/java/com/example/extra/domain/jobpost/dto/controller/JobPostUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/entity/JobPost.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/memberterms/entity/MemberTerms.java
  src/main/java/com/example/extra/domain/role/entity/Role.java
  src/main/java/com/example/extra/domain/role/repository/RoleRepository.java
  src/main/java/com/example/extra/domain/tattoo/entity/Tattoo.java
  src/main/java/com/example/extra/global/entity/BaseEntity.java
Labels: refactor

#148 Feature/fix application request exception
  src/main/java/com/example/extra/domain/applicationrequest/exception/ApplicationRequestErrorCode.java
  src/main/java/com/example/extra/domain/applicationrequest/repository/ApplicationRequestMemberRepository.java
  src/main/java/com/example/extra/domain/applicationrequest/service/impl/ApplicationRequestMemberServiceImpl.java
Labels: feature

#151 Feature/계정 관련 로직 검증 및 리팩토링
  src/main/java/com/example/extra/domain/account/controller/AccountController.java
  src/main/java/com/example/extra/domain/account/dto/controller/AccountCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/controller/AccountLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/service/request/AccountCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/account/exception/AccountErrorCode.java
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
  src/main/java/com/example/extra/domain/refreshtoken/dto/RefreshTokenCreateServiceResponseDto.java
Labels: refactor

#158 Refactor/공고 글 작성 dto 유효성 검증 처리
  src/main/java/com/example/extra/domain/jobpost/dto/controller/JobPostCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/dto/service/request/JobPostCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/jobpost/entity/JobPost.java
  src/main/java/com/example/extra/domain/jobpost/mapper/service/JobPostEntityMapper.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/global/enums/Category.java
Labels: refactor

#155 Feature/validation application request member
  src/main/java/com/example/extra/domain/applicationrequest/controller/ApplicationRequestMemberController.java
  src/main/java/com/example/extra/domain/applicationrequest/dto/controller/ApplicationRequestMemberUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/attendancemanagement/controller/AttendanceManagementController.java
  src/main/java/com/example/extra/domain/attendancemanagement/dto/controller/AttendanceManagementUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/attendancemanagement/dto/controller/AttendanceManagementUpdateMealCountControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardApplyStatusUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainCreateRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/controller/CostumeApprovalBoardExplainUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/domain/role/controller/RoleController.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/role/dto/controller/RoleUpdateControllerRequestDto.java
  src/main/java/com/example/extra/global/exception/CustomValidationException.java
  src/main/java/com/example/extra/global/exception/handler/GlobalExceptionHandler.java
Labels: feature

#159 Refactor/보조 출연자 및 업체 로직 검증 및 리팩토링
  src/main/java/com/example/extra/domain/company/controller/CompanyController.java
  src/main/java/com/example/extra/domain/company/dto/controller/CompanyCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/controller/CompanyLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/service/request/CompanyLoginServiceRequestDto.java
  src/main/java/com/example/extra/domain/company/dto/service/response/CompanyLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/company/dto/service/response/CompanyReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/company/entity/Company.java
  src/main/java/com/example/extra/domain/company/mapper/dto/CompanyDtoMapper.java
  src/main/java/com/example/extra/domain/company/mapper/entity/CompanyEntityMapper.java
  src/main/java/com/example/extra/domain/company/service/CompanyService.java
  src/main/java/com/example/extra/domain/company/service/impl/CompanyServiceImpl.java
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/entity/Member.java
  src/main/java/com/example/extra/domain/member/exception/MemberErrorCode.java
  src/main/java/com/example/extra/domain/member/mapper/entity/MemberEntityMapper.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/domain/tattoo/controller/TattooController.java
  src/main/java/com/example/extra/domain/tattoo/dto/controller/TattooCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/tattoo/dto/service/request/TattooCreateServiceRequestDto.java
  src/main/java/com/example/extra/domain/tattoo/dto/service/response/TattooReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/tattoo/exception/TattooErrorCode.java
  src/main/java/com/example/extra/domain/tattoo/exception/TattooException.java
  src/main/java/com/example/extra/domain/tattoo/repository/TattooRepository.java
  src/main/java/com/example/extra/domain/tattoo/service/TattooService.java
  src/main/java/com/example/extra/domain/tattoo/service/impl/TattooServiceImpl.java
Labels: refactor

#161 Refactor/계정 로그인 에러 처리 반환 변경
  src/main/java/com/example/extra/domain/account/controller/AccountController.java
  src/main/java/com/example/extra/domain/account/dto/controller/AccountCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/controller/AccountLoginControllerRequestDto.java
  src/main/java/com/example/extra/domain/account/dto/service/response/AccountLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/account/exception/AccountErrorCode.java
  src/main/java/com/example/extra/domain/account/mapper/entity/AccountEntityMapper.java
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
Labels: refactor

#167 Feature/fix login
  src/main/java/com/example/extra/domain/account/controller/AccountController.java
  src/main/java/com/example/extra/domain/account/dto/service/response/AccountLoginServiceResponseDto.java
  src/main/java/com/example/extra/domain/account/service/impl/AccountServiceImpl.java
Labels: bug, refactor

#168 Refactor/일정 유효성 검증 및 리팩토링
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/schedule/controller/ScheduleController.java
  src/main/java/com/example/extra/domain/schedule/dto/controller/ScheduleCreateControllerRequestDto.java
  src/main/java/com/example/extra/domain/schedule/dto/controller/ScheduleUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/schedule/dto/service/response/ScheduleReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/schedule/entity/Schedule.java
  src/main/java/com/example/extra/domain/schedule/exception/ScheduleException.java
  src/main/java/com/example/extra/domain/schedule/mapper/dto/ScheduleDtoMapper.java
  src/main/java/com/example/extra/domain/schedule/mapper/service/ScheduleEntityMapper.java
  src/main/java/com/example/extra/domain/schedule/repository/ScheduleRepository.java
  src/main/java/com/example/extra/domain/schedule/service/ScheduleService.java
  src/main/java/com/example/extra/domain/schedule/service/impl/ScheduleServiceImpl.java
Labels: refactor

#173 Feature/공고글 일정 반환 페이징 변경
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
  src/main/java/com/example/extra/domain/schedule/repository/ScheduleRepository.java
Labels: refactor

#175 feature: S3 콘솔에서 폴더 만들어 파일 넣을시 못읽는 문제 해결
  src/main/java/com/example/extra/global/s3/S3Provider.java
Labels: bug

#176 feature : 회사가 작성한 공고글 조회
  src/main/java/com/example/extra/domain/jobpost/controller/JobPostController.java
  src/main/java/com/example/extra/domain/jobpost/repository/JobPostRepository.java
  src/main/java/com/example/extra/domain/jobpost/service/JobPostService.java
  src/main/java/com/example/extra/domain/jobpost/service/impl/JobPostServiceImpl.java
Labels: feature

#178 Feature/use presigned url
  src/main/java/com/example/extra/domain/costumeapprovalboard/controller/CostumeApprovalBoardController.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/dto/service/response/CostumeApprovalBoardMemberReadUrlServiceResponseDto.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/CostumeApprovalBoardService.java
  src/main/java/com/example/extra/domain/costumeapprovalboard/service/impl/CostumeApprovalBoardServiceImpl.java
  src/main/java/com/example/extra/domain/member/controller/MemberController.java
  src/main/java/com/example/extra/domain/member/dto/controller/MemberUpdateControllerRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/request/MemberUpdateServiceRequestDto.java
  src/main/java/com/example/extra/domain/member/dto/service/response/MemberUrlReadServiceResponseDto.java
  src/main/java/com/example/extra/domain/member/service/MemberService.java
  src/main/java/com/example/extra/domain/member/service/impl/MemberServiceImpl.java
  src/main/java/com/example/extra/global/s3/S3Provider.java
Labels: feature
